language: php

php:
  - '5.6'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

notifications:
  email: false

install: 
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - composer check-code
  - php build.php && php test.php
