language: php
sudo: false

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

notifications:
  email: false

install: 
  - composer install

script:
  - ./vendor/bin/phpcs --standard=phpcs.xml -snp --encoding=utf-8 src/ --report-width=150
