language: php
sudo: false

php:
  - '5.6'
  - '7.0'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

notifications:
  email: false

install: 
  - composer install

script:
  - ./vendor/bin/phpcs --standard=phpcs.xml.dist -snp --encoding=utf-8 src/ --report-width=150
  - php build.php && php test.php
